class Focusable:
    def __init__(self): ...

    def draw(self, ctx) -> None: ...

    def handle_button(self, button: str) -> None: ...

    def update(self, delta: int) -> bool:
        return True

    async def start(self) -> None: ...
